### ISSUE TITLE
Tutorial 21 Already Exists Error

### ISSUE THREAD

**Issue by muhammadfhadli1453** [Hvass-Labs/TensorFlow-Tutorials#108]
Hi, can you help me with this problem with machine translation?

When I run model_train.fit I got AlreadyExistError as shown in the picture

![image](https://user-images.githubusercontent.com/24646371/57971117-5649cb00-79bc-11e9-9c32-1f97c7583880.png)

And the detail information looks like this

```
AlreadyExistsError: Resource __per_step_38/training/RMSprop/gradients/decoder_gru1_2/while/ReadVariableOp_6/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var/struct tensorflow::TemporaryVariableOp::TmpVar
	 [[{{node training/RMSprop/gradients/decoder_gru1_2/while/ReadVariableOp_6/Enter_grad/ArithmeticOptimizer/AddOpsRewrite_Add/tmp_var}}]]
```

**Comment by Hvass-Labs** [comment]
I have checked that Tutorial 21 works with TensorFlow version 1.12.0 and Keras version 2.1.6-tf running on Ubuntu 16 with a GTX 1070 GPU.

I don't know what is causing your problem, but everything works fine on my system.

When you file error reports, it is important that you are very specific about the system you are running, the errors you experience, and whether you have made any modifications to the code.

I just wasted an hour checking this works, because you weren't being clear. I'm not happy about that!
