### ISSUE TITLE
 Image Caption works poorly

### ISSUE THREAD

**Issue by ThatNight** [Hvass-Labs/TensorFlow-Tutorials#113]
![64bc524378504a9a3670518751f5c1a](https://user-images.githubusercontent.com/49028624/65650381-32b72100-e03d-11e9-85b7-6fd384e9cbba.png)
![c720b2338b0e1e5d6144471db316301](https://user-images.githubusercontent.com/49028624/65650385-35197b00-e03d-11e9-8751-2a7987215e25.png)
I run according to the tutorial, the result is very poor, can not reach the effect of the tutorial, what should I do? need help

**Comment by Hvass-Labs** [comment]
https://www.youtube.com/watch?v=qlhL9Bx124I

**Comment by ThatNight** [comment]
可以告诉我有什么解决办法吗？重复词出现是什么原因呢

**Comment by ThatNight** [comment]
Can you tell me what the solution is? What are the reasons for the occurrence of repetitions?

**Comment by Hvass-Labs** [comment]
How can you expect me to diagnose the problem with the short message you wrote? If you are running the tutorial exactly like it is in my repository, and you don't make any changes at all, then perhaps it is because you haven't trained it long enough. It has been a long time since I made this tutorial, so I can't remember how long it took for me to train it, but I'm guessing you probably need several hours on a decent GPU - maybe even 10 hours or more.

**Comment by ThatNight** [comment]
![06c5b23423802bcc752853a4b083a3e](https://user-images.githubusercontent.com/49028624/65773335-b3296f00-e16e-11e9-9fa0-f929b12ae0e5.png)
Why is it that training for more than ten hours is still so bad? Is 0.64 loss OK?

**Comment by ThatNight** [comment]
![06c5b23423802bcc752853a4b083a3e](https://user-images.githubusercontent.com/49028624/65773468-f552b080-e16e-11e9-83b9-d983c79ff21a.png)
Why is it that training for more than ten hours is still so bad? Is 0.64 loss OK?

**Comment by Hvass-Labs** [comment]
You expect too much from me. It has probably been more than 1.5 years since I made this and I have done a lot of work since then, and I have a lot of work to do now. You can't expect me to know what is going wrong for you here. But if you find the problem then please write it in this thread so it can help others in the future. Normally when people are having problems with these tutorials, it is because they have made some change they have forgotten, or maybe there is a problem with the dataset.

**Comment by ThatNight** [comment]
Thank you for your suggestion. Sorry to disturb you. Thank you for your tutorial。------------------ 原始邮件 ------------------
发件人: "Hvass-Labs"<notifications@github.com>
发送时间: 2019年9月28日(星期六) 凌晨0:07
收件人: "Hvass-Labs/TensorFlow-Tutorials"<TensorFlow-Tutorials@noreply.github.com>;
抄送: "ThatNight"<2456403321@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Hvass-Labs/TensorFlow-Tutorials]  Image Caption works poorly(#113)



You expect too much from me. It has probably been more than 1.5 years since I made this and I have done a lot of work since then, and I have a lot of work to do now. You can't expect me to know what is going wrong for you here. But if you find the problem then please write it in this thread so it can help others in the future. Normally when people are having problems with these tutorials, it is because they have made some change they have forgotten, or maybe there is a problem with the dataset.
 
&mdash;
