### ISSUE TITLE
Tutorial 23 Error: Supplying multiple axes to axis is no longer supported.

### ISSUE THREAD

**Issue by student1842** [Hvass-Labs/TensorFlow-Tutorials#121]
Hi,I hope you are well.
I get that "supplying multiple axes to axis is no longer supported" error after ''df = weather.load_resampled_data()''

Would it be possible to know how to fix this error please?

![1212](https://user-images.githubusercontent.com/60200115/79057126-75e18600-7c55-11ea-84fc-f31306f35451.jpg)

**Comment by Hvass-Labs** [comment]
Thanks for the error report. It was a tiny fix for a new Pandas version. It should work now. Please try again.

I can see you are new on github. In the future you ought to give more details when filing an error-report, including the version of your installed software. In this case the error is in Pandas, so its version number would be good to know along with TF, numpy, Python, etc., so people can see that you have a recent version installed. Because most error-reports are actually the user's own fault e.g. with old software versions, and it makes my job easier when I know that's not the problem.
