### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by woogyeong23** [Hvass-Labs/TensorFlow-Tutorials#127]
Hello. I'd like to translate this tutorial for my school assignment. Can I simply translate a few things?

**Comment by woogyeong23** [comment]
You don't have to merge..

**Comment by Hvass-Labs** [comment]
Hello,

You can do what you want with these Notebooks, but you should remember to say where you have the original code from.

Some of the Notebooks you are working on are outdated, number 3 on Pretty Tensor and number 3B on the Layers API.

I am hosting the Chinese translation in my own github account, because the original translator suddenly disappeared and I didn't have permission to change the repo, when another translator wanted to continue the work.

https://github.com/Hvass-Labs/TensorFlow-Tutorials-Chinese

I'm not going to merge your pull request. But if you make a github repository in your own account with the Korean translation and name it TensorFlow-Tutorials-Korean, then I can take a look and add a link to the README if the quality looks good. I don't think there's any need to host it in my own github account.
