### ISSUE TITLE
PrittyTensor not working with TensorFlow r1.0

### ISSUE THREAD

**Issue by miga101** [Hvass-Labs/TensorFlow-Tutorials#21]
Here the source code for Tutorial #04 modified version, replacing PrettyTensor with TensorFlow primitives: 

https://github.com/miga101/tf_mnist_cnn

I will try to modify the others too..

**Comment by Hvass-Labs** [comment]
Thanks for the contribution.

Did we discuss this on YouTube already?

The link you posted is broken. Have you changed the PrettyTensor implementation to low-level TensorFlow operations? If so, then it would be better to make a new series of your own tutorials. Because it would be a major change to these tutorials and the videos and Notebooks would no longer be the same.

I agree completely that it is a big problem that changes to TensorFlow breaks the PrettyTensor code. I have to fix the code whenever that happens and it seems like a waste of my time.

But the main problem is actually the lack of management decisions in the TensorFlow team. They should not have developed several different builder API's. The manager should have stopped that. They should only have made one builder API, and then documented it properly, because that would be the API that most people would use to access TensorFlow. Now the whole community suffers from their bad decision to make multiple builder API's that are poorly documented. I have even seen Google engineers that are frustrated by this.

Even so, I would strongly discourage people to use low-level TensorFlow operations to implement entire Neural Networks. It is too laborious and error-prone. Use a builder API instead and have a little patience until it gets updated to support the new TensorFlow version.

**Comment by miga101** [comment]
Hello, yes very frustrated but no time to wait for stable release version, anyway
The link is now working. Thanks!

**Comment by Hvass-Labs** [comment]
You're using a custom builder API in the new code. It looks like it might be the builder API from my Tutorial #02.

Thanks again for the suggestion but I think it is better to use a standard builder API in these tutorials. Then we will just have to wait a while for it to be updated to support the new TF version.
