### ISSUE TITLE
misspelling in 07_Inception_Model

### ISSUE THREAD

**Issue by thrillerist** [Hvass-Labs/TensorFlow-Tutorials#41]
In tutorial 07_Inception_Model

>We can see that it has been squeezed so it is rectangular, and the resolution has been reduced so the image has become more pixelated and grainy.

> The best way to input images to this Inception model, is to pad the image so it is rectangular and then resize the image to 299 x 299 pixels.

I think it should be **_square_** rather than **_rectangular_** here.

**Comment by Hvass-Labs** [comment]
Thanks for the report. I haven't had time to fix this before now. This is such a tiny error that I thought about not fixing it. But I can see that it is confusing so I decided to fix it.

Although this was just 2 words that needed to be replaced, it is not something you can fix in 2 minutes. When I fix a Notebook I also have to rerun and test it. In this case it turned out that that classification scores were slightly different in TensorFlow v. 1.1 which meant that I also had to go through all the text and update that as well. So it ended up taking a long time to fix such a small error.
