### ISSUE TITLE
translate to chinese 

### ISSUE THREAD

**Issue by thrillerist** [Hvass-Labs/TensorFlow-Tutorials#44]
Hi, I have translated this tutorial to chinese,  tutorial #01 - #14 were finished so far.
You can add this link to your repo if you want =)
https://github.com/thrillerist/TensorFlow-Tutorials

**Comment by Hvass-Labs** [comment]
Thanks very much, that is amazing!

I have replaced the link to the Chinese translation in `README.md` because your version is far more complete. I have asked the other author (@naivechen) to please review and contribute to your translations instead. I am sorry that this means some of their work was wasted. It would probably have been better to coordinate the work from the beginning.

I like how you have added 'translated by thrillerist' to the top of each tutorial. I think it is important to give credit to the translator.

Would it be a good idea to also translate the `README.md` file with the installation instructions etc.?

**Comment by thrillerist** [comment]
Thanks man. In fact, he just copy and paste my stuff, we have a conversation yesterday.
I'll translate the `README.md` file later on.

**Comment by Hvass-Labs** [comment]
I noticed he had removed most of the tutorials in the repo and asked why, he said you two had a discussion about 'infringement'. It is impossible for me to judge whether one has copied the other as I don't understand Chinese :-)

I hope people can work together in the future to get the last tutorials translated and reviewed. My goal is to provide tutorials of high quality that will benefit as many people as possible.

Please note that the tutorials are published under the MIT license which also extends to the translations. This means that anyone can use them for anything they want - with only a few conditions (read the license for details). It is of course best to give proper credit to the original author of the tutorials (that is me) and whoever has translated the tutorial. But sometimes I see that people have reused my tutorials without giving me real credit. I can't call the police, so I just take it as a compliment that they found my work so useful that they built on it :-) But giving proper credit is of course the right thing to do.
