### ISSUE TITLE
Connecting

### ISSUE THREAD

**Issue by alexellis** [Hvass-Labs/TensorFlow-Tutorials#50]
Hi @Hvass-Labs,

I've forked your work and packaged it as a "Serverless" OpenFaaS function”. This effectively makes TensorFlow and ImageNet a web-service which takes a URL as input and gives categorisations back as a JSON response.

https://github.com/faas-and-furious/inception-function

I have several opportunities to demonstrate machine-learning with OpenFaaS at Dockercon EU (in two weeks) and KubeCon in December. I'd like to connect and talk more. If you're interested ping alex@openfaas.com or link back-to the repository.

The code has also been packed with Docker which can make the tutorial more accessible on any platform.

**Comment by Hvass-Labs** [comment]
Thanks for making this!

I have added a new file with a list of selected forks which is linked from the main repo's `README.md`:

https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/forks.md

I have not tested your code. I don't know how and I am also pressed for time at the moment. But I did notice you included several files you probably don't need, if you are only using the Inception and VGG16 models.

It has been quite a while since I wrote this code, but I don't think the following are used in `inception.py`:

* `knifey.py`
* `reinforcement_learning.py`
* `convert.py`
* `cifar10.py`

You could also remove more files, but I think that would require for you to remove functions from `inception.py` as well.
