### ISSUE TITLE
Could you update the repo to use tf.layers api instead of PrettyTensor API

### ISSUE THREAD

**Issue by chriszeng87** [Hvass-Labs/TensorFlow-Tutorials#61]
It seems that Tensorflow dev team has already moved tf.contri.layers to tf.layers,so could you update the repo to use tf.layers api instead of PrettyTensor API? Thank you very much!

**Comment by Hvass-Labs** [comment]
I have discussed this in several of the videos on the Layers and Keras APIs as well as the new introduction video. It is a huge mess that the Google developers couldn't decide on a single API and it has caused me and everyone else a lot of problems.

I won't be able to update the tutorials because it would simply take too much time. Remember that this is something I have done without receiving any salary and I have already spent an enormous amount of time on it.

If you want to update the tutorials I can make a link to your fork on GitHub, provided it is of decent quality. I already have a link to a fork with some Keras conversions of the tutorials - perhaps you can just continue that work.

I would recommend using Keras instead of the Layers API, as I've explained in the Keras tutorial video.

**Comment by chriszeng87** [comment]
Anyway, thank you, this tutorial is awesome!
