### ISSUE TITLE
TensorFlow 1.8 doesn't work well with obsolete PrettyTensor

### ISSUE THREAD

**Issue by winstonma** [Hvass-Labs/TensorFlow-Tutorials#68]
I got the following error message from [prettytensor](https://github.com/google/prettytensor)

`AttributeError: module 'tensorflow.python.ops.variable_scope' has no attribute '_VARSCOPE_KEY'`

The major cause of this issue is because prettytensor stopped development for a while and tensorflow 1.8 no longer support _VARSCOPE_KEY ([Github commit](https://github.com/tensorflow/tensorflow/commit/73d17507de23db1c843de587441a958342c2f1e7#diff-57dece591b2185b1c01f712d53baef96)).

From my own perspective there are two possible actions:

1. Replace PrettyTensor with Keras
    To me it is a better solution because it is compatible to future versions of tensorflow. But I guess author has no intention to record the video again
2. Put `tensorflow<1.8` in [requirements.txt](https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/requirements.txt)
    From a tutorial perspective it works but it is not compatible to future versions of tensorflow

**Comment by winstonma** [comment]
Also, starting from tensorflow 1.8, the line `tf.keras.__version__` no longer works

**Comment by Hvass-Labs** [comment]
Thanks for reporting this problem. I'm travelling at the moment so it'll be a while before I can look into this. I'll have to think about what might be the best solution that won't take me too long time to fix.

**Comment by winstonma** [comment]
@Hvass-Labs Thanks for your reply.

Maybe a better solution is to leave the PrettyTensor version in repository (to make sure user understands the idea). At the same time provides the Keras version as an alternative (similar to Tutorial 3, 3-A, 3-B).

**Comment by Hvass-Labs** [comment]
I have fixed this now. It took me almost 3 full work-days to fix this because there were so many issues to fix and things that had to be tested. Several tutorials are not really relevant anymore and it would take too much effort to rewrite them, so I have just added a warning-message to the top of the Notebooks.

Please check if you can get it working now. If there's still problems then reopen this issue.

I thought about changing Tutorial 16 on Reinforcement Learning to use Keras instead but it would simply be too big a job, especially because Keras-RL now exists. So I just removed PrettyTensor from all the code for Tutorial 16 so it uses the Layers API instead. However, I do fear that the Layers API will also be deprecated in the future.

I also had to change the code for all tutorials using MNIST because TensorFlow moved the code into "models" instead, which has an awkward installation procedure to get it working. So I decided to make my own functions for loading the MNIST dataset. This also took some time.

It is a big job to keep the tutorials updated with all the TensorFlow changes and I'm not sure it's worth my time and effort in the long run. The Google Developers should have allocated more resources to proper API design and production of tutorials and educational materials a long time ago. Google has more than USD 100 billion in cash so they can surely afford it. But I think the real problem is that the Google Brain team is so extremely poorly managed.

**Comment by winstonma** [comment]
@Hvass-Labs Thanks for your effort

Really appreciated

**Comment by darvid7** [comment]
I think a similar error is occurring with tutorial 9
