### ISSUE TITLE
Tutorial 14: Parameter "tile_size" is not passed down to proper function.

### ISSUE THREAD

**Issue by d4ichi** [Hvass-Labs/TensorFlow-Tutorials#94]
14_DeepDream.ipynb

Function "optimize_image" is calling "tiled_gradient":

`tiled_gradient(gradient=gradient, image=img)`

But I believe this should be something like:

`tiled_gradient(gradient=gradient, image=img, tile_size=tile_size)`

No matter we set tile_size in "recursive_optimize", that parameter is not passed down to proper function, i think.

Could you check this out please.
Thanks.

**Comment by Hvass-Labs** [comment]
It has been over 2 years since I did this so I honestly can't remember. But I looked at it briefly and it appears you might be right, that the `tile_size` parameter is not passed from the `optimize_image()` function when it calls `tiled_gradient()`. Could you try and change it and report back here what happens? Do you get an error if you change the `tile_size`?

**Comment by Hvass-Labs** [comment]
Thanks for reporting this. It has now been fixed. There does seem to be a difference in the images that are produced depending on the tile-size.

**Comment by d4ichi** [comment]
I'm sorry, it seems I missed notification, didn't realize your comment. Thank you so much for fixing this, also thank you again for this awesome repo.
